FROM python:3.8
WORKDIR /app
COPY . /app
RUN pip install Django Flask Pyramid Tornado Requests Beautifulsoup4 selenium Scrapy numpy pandas matplotlib scikit-learn tensorflow keras torch nltk opencv-python gensim
CMD ["python3"]
